"""add intake models

Revision ID: 13ee8b96fcdb
Revises: af3aba473890
Create Date: 2026-05-16 20:37:15.853697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13ee8b96fcdb'
down_revision: Union[str, Sequence[str], None] = 'af3aba473890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_batch_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('face_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('card_number_encrypted', sa.Text(), nullable=True),
    sa.Column('pin_encrypted', sa.Text(), nullable=True),
    sa.Column('detected_card_number', sa.String(length=255), nullable=True),
    sa.Column('detected_pin', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_batch_id'], ['purchase_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gift_cards_id'), 'gift_cards', ['id'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_batch_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_batch_id'], ['purchase_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_id'), 'receipts', ['id'], unique=False)
    op.create_table('card_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gift_card_id', sa.Integer(), nullable=False),
    sa.Column('image_type', sa.String(length=50), nullable=False),
    sa.Column('original_image_url', sa.String(length=500), nullable=False),
    sa.Column('processed_image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gift_card_id'], ['gift_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_images_id'), 'card_images', ['id'], unique=False)
    op.create_table('extraction_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gift_card_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('extracted_card_number', sa.String(length=255), nullable=True),
    sa.Column('extracted_pin', sa.String(length=255), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gift_card_id'], ['gift_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_attempts_id'), 'extraction_attempts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extraction_attempts_id'), table_name='extraction_attempts')
    op.drop_table('extraction_attempts')
    op.drop_index(op.f('ix_card_images_id'), table_name='card_images')
    op.drop_table('card_images')
    op.drop_index(op.f('ix_receipts_id'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_gift_cards_id'), table_name='gift_cards')
    op.drop_table('gift_cards')
    # ### end Alembic commands ###
