"""add extraction candidates

Revision ID: f07cbbc66e99
Revises: c74316e0a669
Create Date: 2026-05-18 13:34:50.428774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f07cbbc66e99'
down_revision: Union[str, Sequence[str], None] = 'c74316e0a669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extraction_attempt_id', sa.Integer(), nullable=False),
    sa.Column('gift_card_id', sa.Integer(), nullable=False),
    sa.Column('candidate_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['extraction_attempt_id'], ['extraction_attempts.id'], ),
    sa.ForeignKeyConstraint(['gift_card_id'], ['gift_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_candidates_id'), 'extraction_candidates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extraction_candidates_id'), table_name='extraction_candidates')
    op.drop_table('extraction_candidates')
    # ### end Alembic commands ###
